language: python
python:
  - "3.6"

addons:
  apt:
    packages:
    - libleveldb-dev
    - libsqlite3-dev


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e git+https://github.com/CityOfZion/neo-python.git@master#egg=neo-python
  - pip install coveralls

# command to run tests
script:
  - coverage run -m unittest discover boa_test
  - pycodestyle boa
  - pycodestyle boa_test


after_success:
    coveralls
